site_name: TAKANORI NOTE
site_description: "Automatic documentation from sources, for MkDocs."
site_url: https://takavfx.github.io/Takanori-Note/
site_author: Takanori Kishikawa

repo_url: "https://github.com/takavfx/Takanori-Note"
repo_name: "takavfx/Takanori-Note"

# Theme
theme: 
  name: material # mkdocs-materialテーマを有効
  custom_dir: material
  features:
    - tabs
    - instant
  language: ja
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: orange

extra_css:
  - https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
  - stylesheets/extra.css

# Navigation
nav:
  - Home:
    - index.md
  - About:
    - About This Note: 00_About/about_this.md
    - About Me: 00_About/about_me.md
  - Houdini:
    - Houdini: 10_Houdini/index.md
    - Houdini VEX:
      - Houdini VEX: 10_Houdini/VEX/basics.md
      - Houdini VEX Snippets: 10_Houdini/VEX/snippets.md
    - Houdini Python:
      - Houdini Python: 10_Houdini/Python/basics.md
      - Houdini Python Snippets: 10_Houdini/Python/snippets.md
    - Houdini C++:
      - Houdini C++: 10_Houdini/CPP/basics.md
  # - Maya:
  #   - Home: 10_Maya/index.md
  - Programming:
    - Python: 
      - Python: 20_Python/index.md
      - Build Python Packages: 20_Python/build_python_packages.md
      - Build CLI Tools: 20_Python/build_cli_tools.md
  # - Pipeline:
  #   - Pipeline: 20_Pipeline/index.md
  - Research:
    - Machine Learing:
      - 30_MachineLearning/index.md
      - TensorFlow:
        - TensorFlow: 30_MachineLearning/20_TensorFlow/index.md
        - TensorFlow C++: 30_MachineLearning/20_TensorFlow/cpp.md
  - DevEnv:
    - Editor:
      - VS Code:
        # - VSCode: 40_VSCode/index.md
        - VS Code Extensions: 40_VSCode/extensions.md
    - Documentation:
      - mkdocs:
        - mkdocs Setup: 40_mkdocs/index.md

# Extensions
markdown_extensions:
  - admonition # アノテーションブロックを有効
  - codehilite # コードハイライトを有効
  - footnotes # 下部への注釈表記を有効
  - tables # テーブルを有効
  - pymdownx.arithmatex # Arithmatex統合を有効
  - pymdownx.mark # ハイライト機能を有効
  - pymdownx.details # 折り畳みアノテーションを有効
  - pymdownx.keys # キーショートカットの表示
  - pymdownx.tabbed # タブ表示の有効化
  - pymdownx.caret # キャレットを有効化
  - pymdownx.tasklist # タスクリスト表示を有効
  - pymdownx.superfences # admonitionブロック内で複数行の記述を有効
  - pymdownx.tilde # チルダ表記を有効
  - fontawesome_markdown # :<id>:を使用して絵文字の入力できる機能を有効
  - markdown_blockdiag: # Makrkdownダイアグラムを有効
      format: svg
  - pymdownx.emoji: # 絵文字を有効
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true # パーマリンクを有効
  # - awesome-pages


# Plugins
plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
        - ja
  - macros
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         setup_commands:
  #           - import sys
  #           - sys.path.append("docs/20_Python/snippets")
      # watch:
      #   - snippets


# Extra Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/takavfx
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/takavfx
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/auratus
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/takanorikishikawa

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML


# Google Analytics
google_analytics:
  - UA-66121987-6
  - auto