site_name: TAKANORI NOTE
site_description: "Automatic documentation from sources, for MkDocs."
site_url: https://takavfx.github.io/Takanori-Note/
repo_url: "https://github.com/takavfx/Takanori-Note"
repo_name: "takavfx/Takanori-Note"

# Theme
theme: 
  name: material # mkdocs-materialテーマを有効
  custom_dir: overrides
  features:
    - tabs
  language: ja
  name: material
  palette:
    scheme: preference
    primary: deep orange
    accent: orange
  custom_dir: overrides

extra_css:
  - stylesheets/extra.css

# Navigation
nav:
  - Home:
    - index.md
  - About:
    - About This Note: 00_About/about_this.md
    - About Me: 00_About/about_me.md
  - Houdini:
    - Houdini: 10_Houdini/index.md
  # - Maya:
  #   - Home: 10_Maya/index.md
  - Programming:
    - Python: 
      - Python: 20_Python/index.md
      - Build CLI Tool:
        - How To Build: 20_Python/CLI/how-to-build.md
  # - Pipeline:
  #   - Pipeline: 20_Pipeline/index.md
  # - Research:
  #   - MachineLearing: 30_MachineLearning/index.md
  - DevEnv:
    - Editor:
      - VS Code:
        # - VSCode: 40_VSCode/index.md
        - VS Code Extensions: 40_VSCode/extensions.md
    - Documentation:
      - mkdocs:
        - mkdocs: 40_mkdocs/index.md

# Extensions
markdown_extensions:
  - admonition # アノテーションブロックを有効
  - codehilite # コードハイライトを有効
  - footnotes # 下部への注釈表記を有効
  - pymdownx.arithmatex # Arithmatex統合を有効
  - pymdownx.mark # ハイライト機能を有効
  - pymdownx.details # 折り畳みアノテーションを有効
  - pymdownx.keys # キーショートカットの表示
  - pymdownx.emoji: # 絵文字を有効
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.emoji/fontawesome_markdow
  - toc:
      permalink: true # パーマリンクを有効
  # - awesome-pages


# Plugins
plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
        - ja
  - macros
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         setup_commands:
  #           - import sys
  #           - sys.path.append("docs/20_Python/snippets")
      # watch:
      #   - snippets


# Extra Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/takavfx
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/auratus
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/takanorikishikawa

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML


# Google Analytics
google_analytics:
  - 'UA-66121987-6'
  - 'auto'